#pragma once

#include <stdint.h>

#include "driver/i2c_types.h"
#include "driver/uart.h"
#include "hal/adc_types.h"
#include "hal/gpio_types.h"

#define SYNTH_SAMPLE_RATE 48000U
#define SYNTH_BLOCK_FRAMES 128U
#define SYNTH_CHANNEL_COUNT 2U

#define SYNTH_MAX_VOICES 6U
#define SYNTH_CHROMATIC_NOTE_COUNT 12U
#define SYNTH_ACTIVE_OCTAVE_BASE_NOTE 60U
#define SYNTH_DEFAULT_MASTER_VOLUME 0.80f
#define SYNTH_MIX_GAIN 0.85f

#define SYNTH_PCM_BITS 24
#define SYNTH_PCM_MAX_24 ((int32_t)0x7FFFFF)
#define SYNTH_PCM_MIN_24 ((int32_t)-0x800000)
#define SYNTH_I2S_SLOT_BITS 32
#define SYNTH_I2S_24BIT_LEFT_SHIFT 8

#define PCM5102_I2S_BCLK_GPIO GPIO_NUM_16
#define PCM5102_I2S_WS_GPIO GPIO_NUM_17
#define PCM5102_I2S_DOUT_GPIO GPIO_NUM_15

#define MIDI_UART_PORT_NUM UART_NUM_1
#define MIDI_UART_BAUD_RATE 31250
#define MIDI_UART_RX_GPIO GPIO_NUM_18
#define MIDI_UART_TX_GPIO UART_PIN_NO_CHANGE
#define MIDI_UART_BUFFER_SIZE 256

#define VOLUME_POT_ADC_GPIO GPIO_NUM_4
#define VOLUME_POT_ADC_ATTEN ADC_ATTEN_DB_12
#define VOLUME_POT_ADC_MAX_READING 4095.0f
#define VOLUME_POT_SMOOTHING_ALPHA 0.12f

#define INPUT_MODE_SWITCH_GPIO GPIO_NUM_10
#define INPUT_MODE_SWITCH_BUTTON_LEVEL 0

#define BUTTON_INPUT_I2C_PORT I2C_NUM_0
#define BUTTON_INPUT_I2C_SDA_GPIO GPIO_NUM_8
#define BUTTON_INPUT_I2C_SCL_GPIO GPIO_NUM_9
#define BUTTON_INPUT_I2C_SCL_SPEED_HZ 100000U
#define BUTTON_INPUT_MCP23017_ADDRESS 0x20
#define BUTTON_INPUT_DEBOUNCE_BLOCKS 4U
#define BUTTON_INPUT_VELOCITY 127U
